import { getServiceSupabaseClient } from "@/lib/supabase/serviceRoleClient";
import { CleanedProduct } from "./types";

export async function saveCleanedProducts(products: CleanedProduct[]) {
  if (!products || products.length === 0) return;

  const supabase = getServiceSupabaseClient();

  // We rely on the SQL trigger to handle updated_at
  // internal_product_id is generated by DB if omitted on insert
  const { error } = await supabase
    .from("cleaned_products")
    .upsert(products, {
      onConflict: "scraped_product_id",
      ignoreDuplicates: false
    });

  if (error) {
    throw error;
  }
}
