import { createClient } from "@supabase/supabase-js";
import { CleanedProduct } from "./types";

export async function saveCleanedProducts(products: CleanedProduct[]) {
  if (!products || products.length === 0) return;

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  // We rely on the SQL trigger to handle updated_at
  // internal_product_id is generated by DB if omitted on insert
  const { error } = await supabase
    .from("cleaned_products")
    .upsert(products, {
      onConflict: "scraped_product_id",
      ignoreDuplicates: false
    });

  if (error) {
    throw error;
  }
}
